language: node_js
node_js:
  - "16.17.0"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: 101003196-kim
install:
  - npm install
script:
  - npm test