on: push
jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          FIRST_NAME: Mehrad
          LAST_NAME: Heidari
        with:
          script: |
            const { FIRST_NAME, LAST_NAME } = process.env

            console.log(`101332152 ${FIRST_NAME} ${LAST_NAME}`)